### ISSUE TITLE
Mixed display when updating the set of items.

### ISSUE THREAD

**Issue by JoshuaKissoon** [cornflourblue/angu-fixed-header-table#10]
In the initial page load, the table is displayed well and spans the width of the page. However, if I re-load the content via ajax, the display is not clean in that it does not take up the full page width. The body is also positioned differently from the rest of the data.
![screenshot 2015-03-04 12 25 57](https://cloud.githubusercontent.com/assets/1193750/6487801/b3169f52-c269-11e4-8cdf-8cf12ea70b58.png)

**Comment by talski** [comment]
I found a workaround, it's ugly, but it works:

add a empty row at the top of tbody

```html
<tbody>
    <tr class="table-header-first-row"><td></td><td></td><td></td></tr>
```

add columns as needed, and use the following css

```css
.table-header-first-row, .table-header-first-row td {
  margin: 0px !important;
  padding: 0px !important;
  border: 0px !important;
  height: 0px !important;
}
```

Just remember to not remove this line when you update the table content
